version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:3.8  # or any other relevant image
    steps:
      - checkout
      - run:
          name: Create Deployment Directory
          command: mkdir -p DEPLOY-$(date +%F)
      - run:
          name: Build Project
          command: echo "Building the project"
      - run:
          name: Deploy Project
          command: echo "Deploying the project"
  test:
    docker:
      - image: circleci/python:3.8  # or any other relevant image
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: pip install -r requirements.txt
      - run:
          name: Run Tests
          command: python -m unittest discover

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
